### ISSUE TITLE
JAR with eclipse

### ISSUE THREAD

**Issue by KartikChugh** [Tehtafara0/VipSlots#1]
How do I make this a JAR using Eclipse?

**Comment by Tehtafara0** [comment]
Go to your workspace folder and make an another folder with name VipSlots, next go to eclipse > file > new > java project and name the project VipSlots, click finish.
Now you have imported the project. Now you need to add a build path, right click on the project > properties > java build path, then switch to the libraries tab and delete the current craftbukkit-1.7.2-R0.4-20140216.012104-3.jar, you must add your own jar by clicking the button "Add external jars" and select your craftbukkit version. Then click ok on the window, now you need to make the .jar file, make again right click to the project > export. Select Java > JAR file, click next, choose your export destination by using the browse button, and then click finish.
If you want it ready and not to edit it as a jar file you can download it from bukkit : http://dev.bukkit.org/bukkit-plugins/vip-slots/
